sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wangfufan
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tRHLdPog4wM1hdEKMvA
    access-key-secret: 20qMafwAXQCZBLhgbxiUJgmkvrUvgl
    bucket-name: sky-take-out-te
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxd10fe9875f576bac
    secret: 17f12556e08d8633a1345a3bc13edcb6